
name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      base:
        description: 'Vite base to use when building (e.g. / or /levoair/)'
        required: false
        default: '/levoair/'
      custom_domain:
        description: 'Optional custom domain to write into dist/CNAME'
        required: false
        default: ''

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          BASE_INPUT="${{ github.event.inputs.base }}"
          if [ -z "$BASE_INPUT" ]; then
            BASE_INPUT='/levoair/'
          fi
          echo "Using VITE_BASE=$BASE_INPUT"
          export VITE_BASE="$BASE_INPUT"
          npm run build

      - name: Prepare dist (SPA fallback + optional CNAME)
        run: |
          cp -v dist/index.html dist/404.html || true
          if [ "${{ github.event.inputs.custom_domain }}" != "" ]; then
            echo "${{ github.event.inputs.custom_domain }}" > dist/CNAME
            echo "Added CNAME for ${{ github.event.inputs.custom_domain }}"
          fi

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com
